Spring:
  application:
    name: Cart

  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: Warlock@19

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

server:
  port:
    8081